name: dear_flutter
description: "A new Flutter project."
publish_to: 'none' # Tidak dipublish ke pub.dev (private project)
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.2                # Ikon standar iOS
  google_fonts: ^6.1.0                   # Font fleksibel via Google Fonts
  intl: ^0.19.0                          # Formatting tanggal/waktu

  # State Management
  flutter_bloc: ^8.1.3                   # State management berbasis BLoC
  equatable: ^2.0.5                      # Untuk equality check di Bloc/Event/State

  # Dependency Injection
  get_it: ^7.6.7                         # Service Locator (biasa dipasangkan dengan injectable)
  injectable: ^2.3.2                     # Untuk generate registration otomatis (modular)

  # Networking
  dio: ^5.4.1                            # HTTP client modern dengan interceptor
  uuid: ^4.0.0                           # Untuk generate ID unik (misal: ID pesan/chat)
  # Routing
  go_router: ^13.2.0                     # Navigator 2.0 berbasis deklaratif

  # Local Storage / Database
  shared_preferences: ^2.2.2             # Penyimpanan key-value sederhana
  drift: ^2.14.0                         # ORM SQLite untuk Flutter
  drift_sqflite: ^2.0.1                  # Driver SQLite alternatif (jika dibutuhkan)
  sqlite3_flutter_libs: ^0.5.20          # Library SQLite native
  path_provider: ^2.0.11                 # Lokasi file/folder lokal
  path: ^1.8.3                           # Utility untuk manipulasi path

  # JSON Serialization / DTOs
  freezed_annotation: ^2.4.1             # Untuk membuat model immutable
  json_annotation: ^4.9.0                # Untuk serialisasi model
  url_launcher: ^6.2.6                  # Membuka tautan eksternal
  share_plus: ^7.2.1                    # Berbagi konten
  webview_flutter: ^4.4.1              # Menampilkan halaman web dalam aplikasi
  audioplayers: ^5.1.0                  # Pemutar audio sederhana
  flutter_local_notifications: ^19.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0                  # Linter resmi dari Flutter

  # Code Generation (wajib untuk freezed, injectable, drift)
  build_runner: ^2.4.8                   # Tool utama untuk generate file
  freezed: ^2.4.7                        # Codegen untuk model Freezed
  injectable_generator: ^2.4.1           # Codegen untuk dependency injection
  json_serializable: ^6.7.1              # Codegen untuk JSON
  drift_dev: ^2.14.0                     # Codegen untuk ORM Drift
  mocktail: ^1.0.1                       # Untuk mocking di unit test

flutter:
  uses-material-design: true

  # Jika Anda punya asset (gambar, font, data)
  assets:
    - assets/images/
    - assets/fonts/
    - assets/data/

  # (Opsional) Jika menggunakan font custom lokal
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
