name: dear_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.2               # Ikon iOS
  google_fonts: ^6.1.0                  # Untuk memuat font seperti 'Inter'
  intl: ^0.19.0                         # Untuk formatting tanggal/waktu

  # State Management
  flutter_bloc: ^8.1.3                  # Pilihan populer & terstruktur untuk state management

  # Dependency Injection
  get_it: ^7.6.7                        # Service Locator
  injectable: ^2.3.2                    # Code generator untuk get_it

  # Networking
  dio: ^5.4.1                           # Klien HTTP yang powerful dengan interceptor

  # Local Storage
  shared_preferences: ^2.2.2            # Untuk penyimpanan data sederhana (pengganti DataStore)
  drift: ^2.14.0                        # Database lokal (pengganti Room)
  path_provider: ^2.0.11                # Menemukan lokasi file untuk Drift
  path: ^1.8.3                          # Manipulasi path file

  # JSON Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Routing
  go_router: ^13.2.0                    # Routing modern (pengganti Jetpack Navigation)

  # Lainnya
  equatable: ^2.0.5                     # Untuk membandingkan objek secara mudah (berguna di BLoC dan Freezed)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0                 # Linter resmi dari Flutter

  # Code Generators
  build_runner: ^2.4.8
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  drift_dev: ^2.14.0
