// Mocks generated by Mockito 5.4.6 from annotations
// in dear_flutter/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:audio_service/audio_service.dart' as _i14;
import 'package:dear_flutter/data/models/requests.dart' as _i11;
import 'package:dear_flutter/domain/entities/audio_track.dart' as _i7;
import 'package:dear_flutter/domain/entities/home_feed.dart' as _i2;
import 'package:dear_flutter/domain/entities/journal.dart' as _i10;
import 'package:dear_flutter/domain/entities/motivational_quote.dart' as _i3;
import 'package:dear_flutter/domain/entities/song_suggestion.dart' as _i8;
import 'package:dear_flutter/domain/repositories/home_repository.dart' as _i5;
import 'package:dear_flutter/domain/repositories/journal_repository.dart'
    as _i9;
import 'package:dear_flutter/domain/repositories/song_history_repository.dart'
    as _i12;
import 'package:dear_flutter/services/audio_player_handler.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/rxdart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeFeed_0 extends _i1.SmartFake implements _i2.HomeFeed {
  _FakeHomeFeed_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMotivationalQuote_1 extends _i1.SmartFake
    implements _i3.MotivationalQuote {
  _FakeMotivationalQuote_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBehaviorSubject_2<T> extends _i1.SmartFake
    implements _i4.BehaviorSubject<T> {
  _FakeBehaviorSubject_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePublishSubject_3<T> extends _i1.SmartFake
    implements _i4.PublishSubject<T> {
  _FakePublishSubject_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueStream_4<T> extends _i1.SmartFake
    implements _i4.ValueStream<T> {
  _FakeValueStream_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i5.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.HomeFeed> getHomeFeed() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeFeed, []),
            returnValue: _i6.Future<_i2.HomeFeed>.value(
              _FakeHomeFeed_0(this, Invocation.method(#getHomeFeed, [])),
            ),
          )
          as _i6.Future<_i2.HomeFeed>);

  @override
  _i6.Future<_i3.MotivationalQuote> getLatestQuote() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestQuote, []),
            returnValue: _i6.Future<_i3.MotivationalQuote>.value(
              _FakeMotivationalQuote_1(
                this,
                Invocation.method(#getLatestQuote, []),
              ),
            ),
          )
          as _i6.Future<_i3.MotivationalQuote>);

  @override
  _i6.Future<_i7.AudioTrack?> getLatestMusic() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestMusic, []),
            returnValue: _i6.Future<_i7.AudioTrack?>.value(),
          )
          as _i6.Future<_i7.AudioTrack?>);

  @override
  _i6.Future<List<_i8.SongSuggestion>> getMusicSuggestions(String? mood) =>
      (super.noSuchMethod(
            Invocation.method(#getMusicSuggestions, [mood]),
            returnValue: _i6.Future<List<_i8.SongSuggestion>>.value(
              <_i8.SongSuggestion>[],
            ),
          )
          as _i6.Future<List<_i8.SongSuggestion>>);

  @override
  _i6.Future<List<_i7.AudioTrack>> getRadioStation(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getRadioStation, [category]),
            returnValue: _i6.Future<List<_i7.AudioTrack>>.value(
              <_i7.AudioTrack>[],
            ),
          )
          as _i6.Future<List<_i7.AudioTrack>>);

  @override
  _i6.Future<void> triggerMusicGeneration() =>
      (super.noSuchMethod(
            Invocation.method(#triggerMusicGeneration, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> triggerQuoteGeneration() =>
      (super.noSuchMethod(
            Invocation.method(#triggerQuoteGeneration, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i9.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i10.Journal>> getJournals() =>
      (super.noSuchMethod(
            Invocation.method(#getJournals, []),
            returnValue: _i6.Stream<List<_i10.Journal>>.empty(),
          )
          as _i6.Stream<List<_i10.Journal>>);

  @override
  _i6.Future<void> createJournal(_i11.CreateJournalRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createJournal, [request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncJournals() =>
      (super.noSuchMethod(
            Invocation.method(#syncJournals, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SongHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongHistoryRepository extends _i1.Mock
    implements _i12.SongHistoryRepository {
  MockSongHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> addTrack(_i7.AudioTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#addTrack, [track]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  List<_i7.AudioTrack> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: <_i7.AudioTrack>[],
          )
          as List<_i7.AudioTrack>);
}

/// A class which mocks [AudioPlayerHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerHandler extends _i1.Mock
    implements _i13.AudioPlayerHandler {
  MockAudioPlayerHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BehaviorSubject<_i14.PlaybackState> get playbackState =>
      (super.noSuchMethod(
            Invocation.getter(#playbackState),
            returnValue: _FakeBehaviorSubject_2<_i14.PlaybackState>(
              this,
              Invocation.getter(#playbackState),
            ),
          )
          as _i4.BehaviorSubject<_i14.PlaybackState>);

  @override
  _i4.BehaviorSubject<List<_i14.MediaItem>> get queue =>
      (super.noSuchMethod(
            Invocation.getter(#queue),
            returnValue: _FakeBehaviorSubject_2<List<_i14.MediaItem>>(
              this,
              Invocation.getter(#queue),
            ),
          )
          as _i4.BehaviorSubject<List<_i14.MediaItem>>);

  @override
  _i4.BehaviorSubject<String> get queueTitle =>
      (super.noSuchMethod(
            Invocation.getter(#queueTitle),
            returnValue: _FakeBehaviorSubject_2<String>(
              this,
              Invocation.getter(#queueTitle),
            ),
          )
          as _i4.BehaviorSubject<String>);

  @override
  _i4.BehaviorSubject<_i14.MediaItem?> get mediaItem =>
      (super.noSuchMethod(
            Invocation.getter(#mediaItem),
            returnValue: _FakeBehaviorSubject_2<_i14.MediaItem?>(
              this,
              Invocation.getter(#mediaItem),
            ),
          )
          as _i4.BehaviorSubject<_i14.MediaItem?>);

  @override
  _i4.BehaviorSubject<_i14.AndroidPlaybackInfo> get androidPlaybackInfo =>
      (super.noSuchMethod(
            Invocation.getter(#androidPlaybackInfo),
            returnValue: _FakeBehaviorSubject_2<_i14.AndroidPlaybackInfo>(
              this,
              Invocation.getter(#androidPlaybackInfo),
            ),
          )
          as _i4.BehaviorSubject<_i14.AndroidPlaybackInfo>);

  @override
  _i4.BehaviorSubject<_i14.RatingStyle> get ratingStyle =>
      (super.noSuchMethod(
            Invocation.getter(#ratingStyle),
            returnValue: _FakeBehaviorSubject_2<_i14.RatingStyle>(
              this,
              Invocation.getter(#ratingStyle),
            ),
          )
          as _i4.BehaviorSubject<_i14.RatingStyle>);

  @override
  _i4.PublishSubject<dynamic> get customEvent =>
      (super.noSuchMethod(
            Invocation.getter(#customEvent),
            returnValue: _FakePublishSubject_3<dynamic>(
              this,
              Invocation.getter(#customEvent),
            ),
          )
          as _i4.PublishSubject<dynamic>);

  @override
  _i4.BehaviorSubject<dynamic> get customState =>
      (super.noSuchMethod(
            Invocation.getter(#customState),
            returnValue: _FakeBehaviorSubject_2<dynamic>(
              this,
              Invocation.getter(#customState),
            ),
          )
          as _i4.BehaviorSubject<dynamic>);

  @override
  _i6.Future<void> playPlaylist(List<_i7.AudioTrack>? tracks) =>
      (super.noSuchMethod(
            Invocation.method(#playPlaylist, [tracks]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playFromYoutubeId(
    String? youtubeId,
    _i7.AudioTrack? track,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#playFromYoutubeId, [youtubeId, track]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> prepare() =>
      (super.noSuchMethod(
            Invocation.method(#prepare, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> prepareFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#prepareFromMediaId, [mediaId, extras]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> prepareFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#prepareFromSearch, [query, extras]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> prepareFromUri(Uri? uri, [Map<String, dynamic>? extras]) =>
      (super.noSuchMethod(
            Invocation.method(#prepareFromUri, [uri, extras]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#playFromMediaId, [mediaId, extras]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#playFromSearch, [query, extras]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playFromUri(Uri? uri, [Map<String, dynamic>? extras]) =>
      (super.noSuchMethod(
            Invocation.method(#playFromUri, [uri, extras]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playMediaItem(_i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#playMediaItem, [mediaItem]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> click([_i14.MediaButton? button = _i14.MediaButton.media]) =>
      (super.noSuchMethod(
            Invocation.method(#click, [button]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addQueueItem(_i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#addQueueItem, [mediaItem]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addQueueItems(List<_i14.MediaItem>? mediaItems) =>
      (super.noSuchMethod(
            Invocation.method(#addQueueItems, [mediaItems]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> insertQueueItem(int? index, _i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#insertQueueItem, [index, mediaItem]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateQueue(List<_i14.MediaItem>? queue) =>
      (super.noSuchMethod(
            Invocation.method(#updateQueue, [queue]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateMediaItem(_i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateMediaItem, [mediaItem]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeQueueItem(_i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#removeQueueItem, [mediaItem]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeQueueItemAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeQueueItemAt, [index]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> skipToNext() =>
      (super.noSuchMethod(
            Invocation.method(#skipToNext, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> skipToPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#skipToPrevious, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fastForward() =>
      (super.noSuchMethod(
            Invocation.method(#fastForward, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> rewind() =>
      (super.noSuchMethod(
            Invocation.method(#rewind, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> skipToQueueItem(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#skipToQueueItem, [index]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setRating(
    _i14.Rating? rating, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#setRating, [rating, extras]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setCaptioningEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setCaptioningEnabled, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setRepeatMode(_i14.AudioServiceRepeatMode? repeatMode) =>
      (super.noSuchMethod(
            Invocation.method(#setRepeatMode, [repeatMode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setShuffleMode(_i14.AudioServiceShuffleMode? shuffleMode) =>
      (super.noSuchMethod(
            Invocation.method(#setShuffleMode, [shuffleMode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> seekBackward(bool? begin) =>
      (super.noSuchMethod(
            Invocation.method(#seekBackward, [begin]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> seekForward(bool? begin) =>
      (super.noSuchMethod(
            Invocation.method(#seekForward, [begin]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeed, [speed]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<dynamic> customAction(
    String? name, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#customAction, [name, extras]),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<void> onTaskRemoved() =>
      (super.noSuchMethod(
            Invocation.method(#onTaskRemoved, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> onNotificationDeleted() =>
      (super.noSuchMethod(
            Invocation.method(#onNotificationDeleted, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i14.MediaItem>> getChildren(
    String? parentMediaId, [
    Map<String, dynamic>? options,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getChildren, [parentMediaId, options]),
            returnValue: _i6.Future<List<_i14.MediaItem>>.value(
              <_i14.MediaItem>[],
            ),
          )
          as _i6.Future<List<_i14.MediaItem>>);

  @override
  _i4.ValueStream<Map<String, dynamic>> subscribeToChildren(
    String? parentMediaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToChildren, [parentMediaId]),
            returnValue: _FakeValueStream_4<Map<String, dynamic>>(
              this,
              Invocation.method(#subscribeToChildren, [parentMediaId]),
            ),
          )
          as _i4.ValueStream<Map<String, dynamic>>);

  @override
  _i6.Future<_i14.MediaItem?> getMediaItem(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaItem, [mediaId]),
            returnValue: _i6.Future<_i14.MediaItem?>.value(),
          )
          as _i6.Future<_i14.MediaItem?>);

  @override
  _i6.Future<List<_i14.MediaItem>> search(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query, extras]),
            returnValue: _i6.Future<List<_i14.MediaItem>>.value(
              <_i14.MediaItem>[],
            ),
          )
          as _i6.Future<List<_i14.MediaItem>>);

  @override
  _i6.Future<void> androidAdjustRemoteVolume(
    _i14.AndroidVolumeDirection? direction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#androidAdjustRemoteVolume, [direction]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> androidSetRemoteVolume(int? volumeIndex) =>
      (super.noSuchMethod(
            Invocation.method(#androidSetRemoteVolume, [volumeIndex]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
