"""add_stream_url_to_music_tracks

Revision ID: b3dd0d516a13
Revises: d480e091ae70
Create Date: 2025-07-04 23:56:18.838005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3dd0d516a13'
down_revision: Union[str, Sequence[str], None] = 'd480e091ae70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musictracks', sa.Column('stream_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musictracks', 'stream_url')
    # ### end Alembic commands ###
