"""<new data>

Revision ID: c06414aeceb9
Revises: 35bf2bfd0edb
Create Date: 2025-07-05 15:59:02.821039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06414aeceb9'
down_revision: Union[str, Sequence[str], None] = '35bf2bfd0edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musictracks', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musictracks', 'status')
    # ### end Alembic commands ###
