"""add youtube_id to audiotracks

Revision ID: ccafebe2004a
Revises: d0a3eee022e6
Create Date: 2025-07-01 01:35:41.987505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccafebe2004a'
down_revision: Union[str, Sequence[str], None] = 'd0a3eee022e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiotracks', sa.Column('youtube_id', sa.String(), nullable=True))
    op.drop_column('audiotracks', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiotracks', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('audiotracks', 'youtube_id')
    # ### end Alembic commands ###
